// GENERATED by scripts/gen-slug-overrides.mjs — do not edit by hand.
// Headings whose slug the base rule in slugify.ts does not reproduce. Values are the ids
// the live Mintlify site emits, so anchors stay link-compatible.
// base rule matched 290/293 headings; 3 overrides below.
export const SLUG_OVERRIDES: Record<string, string> = {
  "🛠 What’s Next?": "-what’s-next",
  "Create a new change (branch):": "create-a-new-change-branch-",
  "MATCH ... CREATE ... and MATCH ... CREATE ... RETURN ... queries": "match-create-and-match-create-return-queries",
};
